export const SET_CANVAS_CONTEXT = 'SET_CANVAS_CONTEXT';
export const SET_CANVAS_CONTEXT_3D = 'SET_CANVAS_CONTEXT_3D';
export const SET_CANVAS_SIZE = 'SET_CANVAS_SIZE';
export const SET_TARGET_TIME = 'SET_TARGET_TIME';
export const START_ANIMATION = 'START_ANIMATION';
export const STOP_ANIMATION = 'STOP_ANIMATION';
export const TICK = 'TICK';
